platform :ios, '9.0'

target 'Compress-Upload-CocoaLumberjack_Example' do
  pod 'Compress-Upload-CocoaLumberjack', :path => '../'

  target 'Compress-Upload-CocoaLumberjack_Tests' do
    inherit! :search_paths

    pod 'Expecta'
  end
end

post_install do |installer_representation|
  
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = 9.0
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
      
      if target.name == "CocoaLumberjack"
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = 9.0
        config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)', '-Wno-strict-prototypes', '-Wno-deprecated-declarations', '-Wno-deprecated-implementations', '-Wno-implicit-retain-self']
        
      end
    end
  end
end
